"""
developer_db.py — Cơ sở dữ liệu phân tích chủ đầu tư BĐS TP.HCM
Đánh giá: uy tín, chất lượng vận hành, lịch sử pháp lý (T5/2026)
"""

# legal_status: "clean" | "caution" | "warning" | "red"
# delivery_risk: "low" | "medium" | "high"
# rating / operations: 1–5

DEVELOPERS = {
    "Vingroup": {
        "rating": 5,
        "credibility": "Tập đoàn tư nhân lớn nhất VN, niêm yết quốc tế (VIC), vốn hóa hàng đầu HOSE.",
        "operations": 5,
        "operations_note": "Vận hành Vinhomes tiêu chuẩn 5★, phần mềm VinHome quản lý tích hợp, an ninh 24/7.",
        "legal_status": "clean",
        "legal_note": "Pháp lý minh bạch, công ty đại chúng phải công bố thông tin. Chưa có vụ kiện lớn liên quan bàn giao hoặc sổ hồng.",
        "delivery_risk": "low",
        "delivery_note": "Lịch sử đúng tiến độ hoặc sớm hơn cam kết. VGP bàn giao đúng 2020–2022.",
        "notable": "Đối tác Nhật Bản (Samty Corp) tại phân khu Origami & Opus One nâng tiêu chuẩn vận hành lên mức quốc tế.",
        "projects_hcm": ["Vinhomes Grand Park (Thủ Đức)"],
    },
    "Phú Mỹ Hưng Corp": {
        "rating": 5,
        "credibility": "Liên doanh Đài Loan–VN (Central Trading & Development). Chuẩn đô thị quốc tế hơn 30 năm tại HCMC.",
        "operations": 5,
        "operations_note": "Phí quản lý cao (~50–90k/m²/tháng) nhưng chất lượng vận hành xuất sắc. Cộng đồng expat đánh giá tốt nhất TP.",
        "legal_status": "clean",
        "legal_note": "Toàn bộ dự án PMH có đầy đủ pháp lý. Sổ hồng vĩnh viễn, không vướng tranh chấp.",
        "delivery_risk": "low",
        "delivery_note": "Không có ghi nhận chậm bàn giao trong lịch sử 30+ năm hoạt động.",
        "notable": "Sky Garden, Riverside Residence trong khu PMH — chuẩn cao nhất phân khúc 3–10 tỷ Q7.",
        "projects_hcm": ["Sky Garden 3 (Q7)", "Riverside Residence (Q7)"],
    },
    "Nam Long Group": {
        "rating": 4,
        "credibility": "Niêm yết (NLG), chuyên phân khúc vừa túi tiền & đô thị tích hợp. Đối tác Nhật: Hankyu Hanshin, Nishi Nippon RR.",
        "operations": 4,
        "operations_note": "Quản lý chuyên nghiệp, thương hiệu EZ Land cho phân khúc mid-end. Phí vận hành hợp lý ~10–15k/m².",
        "legal_status": "clean",
        "legal_note": "Công ty đại chúng, pháp lý minh bạch. Akari City & Mizuki Park sổ hồng đầy đủ từng block.",
        "delivery_risk": "low",
        "delivery_note": "Bàn giao đúng hoặc trễ nhẹ (≤3 tháng). Ehome 3 (2016), Akari (2021), Mizuki (2020) đều đúng tiến độ.",
        "notable": "Mô hình đô thị xanh tích hợp cùng đối tác Nhật là lợi thế khác biệt dài hạn. EZ Land (Hausneo, Hausbelo) là brand mid-end chất lượng.",
        "projects_hcm": ["Akari City (Bình Tân)", "EHome 3 (Bình Tân)", "Mizuki Park (Bình Chánh)", "Hausneo (Thủ Đức)", "Hausbelo (Thủ Đức)"],
    },
    "EZ Land (Nam Long)": {
        "rating": 4,
        "credibility": "Thương hiệu con của Nam Long Group, chuyên phân khúc mid-end Thủ Đức (Q9 cũ). Được hỗ trợ bởi uy tín NLG.",
        "operations": 4,
        "operations_note": "Tương đương tiêu chuẩn Nam Long, cùng hệ thống quản lý. Hausneo có phí vận hành ~12k/m²/tháng.",
        "legal_status": "clean",
        "legal_note": "Pháp lý sạch, kế thừa từ Nam Long. Hausneo đã có sổ hồng từng căn.",
        "delivery_risk": "low",
        "delivery_note": "Hausneo bàn giao Q3/2021 đúng cam kết. Hausbelo đang xây, dự kiến 2026.",
        "notable": "Giá tốt nhất khu vực Q9 cũ — Thủ Đức với tiêu chuẩn đối tác Nhật. Thích hợp đầu tư cho thuê dài hạn.",
        "projects_hcm": ["Hausneo (Thủ Đức)", "Hausbelo (Thủ Đức)"],
    },
    "Gamuda Land": {
        "rating": 5,
        "credibility": "Tập đoàn Malaysia niêm yết quốc tế (Gamuda Berhad). Top 5 developer ASEAN về đô thị xanh.",
        "operations": 5,
        "operations_note": "Tiêu chuẩn ASEAN — Celadon City vận hành bởi Gamuda Property Management, rating 4.5★ trên Google Reviews.",
        "legal_status": "clean",
        "legal_note": "Tuân thủ đầy đủ pháp luật VN, không có tranh chấp. Celadon City đã cấp sổ hồng toàn bộ các block hoàn thành.",
        "delivery_risk": "low",
        "delivery_note": "Bàn giao đúng cam kết theo từng phân khu. Khu Emerald, Sapphire, Diamond đã hoàn thành đúng tiến độ.",
        "notable": "Khu đô thị 82 ha chuẩn Malaysia — tiêu chuẩn sống cao nhất Tân Phú. Cộng đồng cư dân ổn định, thanh khoản tốt.",
        "projects_hcm": ["Celadon City (Tân Phú)"],
    },
    "Him Lam Land": {
        "rating": 4,
        "credibility": "Thành viên Tập đoàn Him Lam, hoạt động BĐS từ 1994. Uy tín lâu đời tại HCMC và Hà Nội.",
        "operations": 4,
        "operations_note": "Vận hành ổn định, phí quản lý trung bình ~10–12k/m². Cư dân Dragon City đánh giá tốt về an ninh và cảnh quan.",
        "legal_status": "clean",
        "legal_note": "Pháp lý sạch qua các dự án. Him Lam Riverside và Dragon Hill 2 đều có sổ hồng đầy đủ.",
        "delivery_risk": "low",
        "delivery_note": "Lịch sử 30 năm không có ghi nhận chậm bàn giao đáng kể. Dragon Hill 2 bàn giao 2020 đúng kế hoạch.",
        "notable": "Dragon City (Him Lam Riverside + Dragon Hill 1&2) là quần thể 3 dự án lớn nhất Nhà Bè — thanh khoản cao, cộng đồng ổn định.",
        "projects_hcm": ["Him Lam Riverside (Nhà Bè)", "Dragon Hill 2 (Nhà Bè)", "Him Lam Chợ Lớn (Q6)"],
    },
    "TTC Land": {
        "rating": 4,
        "credibility": "Công ty con Tập đoàn TTC (Thành Thành Công). Niêm yết (SCR). Chuyên chuỗi Carillon, Charmington.",
        "operations": 4,
        "operations_note": "Vận hành chuỗi Carillon tốt, phí quản lý ~10–13k/m². Carillon 5 & 7 được cư dân đánh giá 4/5 về bảo trì.",
        "legal_status": "clean",
        "legal_note": "Công ty đại chúng, pháp lý ổn. Carillon 5, 7 đã có sổ hồng. Charmington Tân Bình chưa ghi nhận vướng mắc.",
        "delivery_risk": "low",
        "delivery_note": "Bàn giao đúng tiến độ trong lịch sử. Carillon 7 bàn giao 2020, Carillon 5 bàn giao 2018 đúng hạn.",
        "notable": "Chuỗi Carillon là thương hiệu tin cậy nhất Tân Phú. TTC đang cơ cấu lại để tập trung BĐS thương mại cao cấp.",
        "projects_hcm": ["Carillon 7 (Tân Phú)", "Carillon 5 (Tân Phú)", "Charmington Tân Bình (Tân Bình)"],
    },
    "Hưng Thịnh Corp": {
        "rating": 3,
        "credibility": "Một trong top 5 developer VN theo doanh số. Phủ rộng từ Q7 đến các tỉnh. Tái cơ cấu tài chính 2022–2024.",
        "operations": 3,
        "operations_note": "Vận hành trung bình, phí ~10k/m². Moonlight Residences được đánh giá ổn. Q7 Saigon Riverside chưa có nhiều phản hồi (mới BG 2022).",
        "legal_status": "caution",
        "legal_note": "⚠️ Giai đoạn 2022–2024 gặp khó khăn dòng tiền, một số dự án trái phiếu bị chậm trả. Đang trong lộ trình tái cơ cấu. Dự án trong danh sách (Q7 Riverside, Moonlight) đã BG và có sổ hồng — rủi ro thấp hơn dự án mới.",
        "delivery_risk": "medium",
        "delivery_note": "Các dự án đã bàn giao trước 2022 ổn định. Dự án mới sau 2022 có rủi ro chậm bàn giao cao hơn.",
        "notable": "Rủi ro tập trung ở dự án chưa BG. Q7 Saigon Riverside và Moonlight đã có sổ hồng nên rủi ro thứ cấp thấp.",
        "projects_hcm": ["Q7 Saigon Riverside (Q7)", "Moonlight Residences (Thủ Đức)"],
    },
    "Novaland": {
        "rating": 3,
        "credibility": "Từng là top 3 developer VN. Đang tái cơ cấu nợ trái phiếu ~10,000 tỷ (2022–2025). Thương hiệu vẫn mạnh nhưng tài chính rủi ro.",
        "operations": 3,
        "operations_note": "Dự án đã BG (Sunrise City View 2015, The Sun Avenue 2018, Richstar 2018) vận hành bởi Novaland Services — chất lượng trung bình–tốt. Phí ~12–18k/m².",
        "legal_status": "caution",
        "legal_note": "⚠️ Novaland bị SEC điều tra (2022), tái cơ cấu nợ trái phiếu đến 2025. Các dự án cũ đã BG trong danh sách (Richstar, Sun Avenue, Sunrise City View) có sổ hồng — rủi ro pháp lý thấp. KHÔNG mua dự án Novaland chưa bàn giao trong giai đoạn này.",
        "delivery_risk": "medium",
        "delivery_note": "Dự án đã BG: an toàn. Dự án mới/chưa BG: rủi ro cao do tình hình tài chính. Các dự án trong danh sách đều đã BG trước 2022.",
        "notable": "Mua thứ cấp các dự án đã BG của Novaland là an toàn. Tránh mua đặt cọc dự án mới cho đến khi tài chính ổn định.",
        "projects_hcm": ["Sunrise City View (Q7)", "The Sun Avenue (Thủ Đức)", "Richstar (Tân Phú)"],
    },
    "Quốc Cường Gia Lai": {
        "rating": 2,
        "credibility": "Niêm yết (QCG). Chủ yếu hoạt động BĐS Q7 và các tỉnh. Năm 2024 gặp biến cố pháp lý lớn.",
        "operations": 3,
        "operations_note": "Lavida Plus và Central Premium vận hành bởi đơn vị thứ 3. Chất lượng phản hồi từ cư dân ở mức trung bình.",
        "legal_status": "warning",
        "legal_note": "🚨 Bà Nguyễn Thị Như Loan (CEO/Chủ tịch) bị khởi tố T9/2024 liên quan dự án Phước Kiểng (Nhà Bè) — tội 'vi phạm quy định về sử dụng đất'. Cổ phiếu QCG giảm mạnh. Lavida Plus (Q7) và Central Premium (Q8) là dự án đã BG có sổ hồng, ít ảnh hưởng trực tiếp hơn. Cần thẩm định kỹ trước khi mua.",
        "delivery_risk": "high",
        "delivery_note": "Dự án mới của QCG có rủi ro rất cao. Lavida Plus (2021) và Central Premium (2019) đã BG — an toàn hơn cho giao dịch thứ cấp.",
        "notable": "Chỉ mua thứ cấp các dự án đã BG và có sổ hồng. Tuyệt đối không đặt cọc dự án mới hoặc chuyển nhượng hợp đồng.",
        "projects_hcm": ["Lavida Plus (Q7)", "Central Premium (Q8)"],
    },
    "Sunshine Group": {
        "rating": 3,
        "credibility": "Tập đoàn tư nhân quy mô lớn, đang mở rộng HCMC từ 2019. Sunshine Sky City là dự án flagship Q7.",
        "operations": 3,
        "operations_note": "Chưa có nhiều dự án BG tại HCMC để đánh giá vận hành. Sunshine Group tại HN có phí quản lý cao ~18–25k/m².",
        "legal_status": "caution",
        "legal_note": "⚠️ Một số dự án tại Hà Nội chậm BG và vướng pháp lý (Sunshine City HN chậm sổ hồng). Sunshine Sky City Q7 đang xây dựng — chưa có lịch sử BG tại HCMC để đánh giá.",
        "delivery_risk": "medium",
        "delivery_note": "Sunshine Sky City dự kiến BG Q3/2027. Rủi ro chậm BG ở mức trung bình dựa trên lịch sử HN. Cần theo dõi tiến độ xây dựng.",
        "notable": "Dự án off-plan — nên mua khi đã đủ điều kiện ký HĐMB chính thức và có tiến độ xây dựng rõ ràng.",
        "projects_hcm": ["Sunshine Sky City (Q7)"],
    },
    "Vạn Thái Land": {
        "rating": 3,
        "credibility": "Developer quy mô vừa chuyên thị trường Q8 và Tân Phú. Topaz Elite và Topaz Garden là sản phẩm chủ lực.",
        "operations": 3,
        "operations_note": "Vận hành trung bình, phí ~8–10k/m². Topaz Elite được đánh giá 3.5/5 về bảo trì và dịch vụ.",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn, không có vụ kiện đáng kể. Topaz Elite (2019) và Topaz Garden (2015) đều có sổ hồng.",
        "delivery_risk": "low",
        "delivery_note": "Tất cả dự án trong danh sách đã BG và có sổ hồng. Rủi ro thứ cấp thấp.",
        "notable": "Giá tốt nhất Q8 cho phân khúc 3–4 tỷ. Phù hợp đầu tư cho thuê nhờ thanh khoản ổn định.",
        "projects_hcm": ["Topaz Elite (Q8)", "Topaz Garden (Tân Phú)"],
    },
    "Hoàng Anh Gia Lai": {
        "rating": 2,
        "credibility": "Tập đoàn HAGL (HAG/HNG) từng lớn mạnh, nay đang thoái lui BĐS để tập trung nông nghiệp. Nợ xấu lớn.",
        "operations": 2,
        "operations_note": "Hoàng Anh Thanh Bình (Q7, 2012) vận hành xuống cấp do thiếu đầu tư tái thiết. Phí quản lý thấp nhưng chất lượng tương đương.",
        "legal_status": "caution",
        "legal_note": "⚠️ HAGL đang tái cơ cấu nợ ~28,000 tỷ với các ngân hàng. Dự án Hoàng Anh Thanh Bình (2012) đã có sổ hồng — an toàn giao dịch. Không liên quan trực tiếp đến nợ nhóm.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG từ 2012, không có rủi ro bàn giao. Rủi ro chính là chất lượng vận hành và thanh khoản thứ cấp.",
        "notable": "Giá thứ cấp rất tốt do thương hiệu mờ dần. Phù hợp mua ở thực, không phù hợp đầu tư lướt sóng.",
        "projects_hcm": ["Hoàng Anh Thanh Bình (Q7)"],
    },
    "Đức Khải": {
        "rating": 2,
        "credibility": "Developer chủ yếu khu Q7-PMH. Era Town (2015) là dự án lớn nhất. Công ty gặp nhiều khó khăn tài chính sau 2018.",
        "operations": 2,
        "operations_note": "Vận hành Era Town ở mức trung bình thấp, thiếu đầu tư nâng cấp. Phản hồi cư dân về bảo trì không tốt.",
        "legal_status": "warning",
        "legal_note": "🚨 Lãnh đạo Đức Khải bị khởi tố về tội 'lừa đảo chiếm đoạt tài sản' liên quan đến dự án Era Town (2021–2022). Dự án đã BG và có sổ hồng riêng — giao dịch thứ cấp an toàn hơn nhưng cần thẩm định kỹ pháp lý căn hộ cụ thể.",
        "delivery_risk": "low",
        "delivery_note": "Era Town đã BG 2015, có sổ hồng. Rủi ro bàn giao không còn áp dụng. Rủi ro là thanh khoản thứ cấp thấp.",
        "notable": "Giá thứ cấp rẻ nhất PMH-adjacent (~50tr/m²) nhưng kèm rủi ro danh tiếng developer. Phù hợp mua ở thực, giá tốt.",
        "projects_hcm": ["Era Town (Q7)"],
    },
    "CII": {
        "rating": 3,
        "credibility": "Công ty Cổ phần Đầu tư Hạ tầng Kỹ thuật TP.HCM (CII), niêm yết. Chuyên hạ tầng và BĐS ven sông.",
        "operations": 3,
        "operations_note": "City Gate Towers và Diamond Riverside vận hành bởi đơn vị độc lập. Chất lượng trung bình, phí ~9–11k/m².",
        "legal_status": "clean",
        "legal_note": "Công ty đại chúng, pháp lý ổn. City Gate Towers và Diamond Riverside có sổ hồng. Dự án ven Kênh Đôi được hưởng lợi từ quy hoạch cải tạo.",
        "delivery_risk": "low",
        "delivery_note": "Các dự án đã BG đúng tiến độ. Diamond Riverside (2022) BG đúng hạn.",
        "notable": "Lợi thế lớn: dự án cải tạo Kênh Đôi 7,300 tỷ sẽ nâng giá trị khu vực đáng kể sau 2026–2027.",
        "projects_hcm": ["City Gate Towers (Q8)", "Diamond Riverside (Q8)"],
    },
    "Xuân Mai Corp": {
        "rating": 3,
        "credibility": "Tập đoàn Xuân Mai, chuyên xây dựng và phát triển nhà ở thương mại/xã hội. Eco Green Saigon là flagship HCMC.",
        "operations": 3,
        "operations_note": "Vận hành Eco Green Saigon bởi đơn vị nội bộ. Công viên nội khu 5000m² là điểm nhấn. Phí ~11–13k/m².",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn, không có vụ kiện đáng kể. Eco Green Saigon (BG 2022) đang cấp sổ hồng theo từng block.",
        "delivery_risk": "low",
        "delivery_note": "BG 2022 đúng tiến độ. Một số căn chậm sổ hồng ~6 tháng so với cam kết — không nghiêm trọng.",
        "notable": "Tỷ lệ xanh hóa cao nhất Q7 — lợi thế lớn trong dài hạn. Thanh khoản cho thuê tốt nhờ cộng đồng sinh thái.",
        "projects_hcm": ["Eco Green Saigon (Q7)"],
    },
    "DRH Corp": {
        "rating": 3,
        "credibility": "Công ty CP Đầu tư Căn nhà Mơ Ước (DRH Holdings), niêm yết (DRH). Quy mô vừa, chuyên Q8.",
        "operations": 3,
        "operations_note": "Aurora Residences (2023) còn khá mới, chưa đủ thời gian đánh giá vận hành. Phản hồi ban đầu của cư dân ổn.",
        "legal_status": "clean",
        "legal_note": "Công ty đại chúng. Aurora Residences đã có sổ hồng (2023). Pháp lý sạch.",
        "delivery_risk": "low",
        "delivery_note": "Aurora BG 2023 đúng tiến độ cam kết. Rủi ro thấp.",
        "notable": "Giá tốt nhất Q8 cho dự án mới (2023). Tiềm năng hưởng lợi từ cải tạo Kênh Đôi và quy hoạch Q8.",
        "projects_hcm": ["Aurora Residences (Q8)"],
    },
    "DHA Corp": {
        "rating": 3,
        "credibility": "Công ty CP Đầu tư & Phát triển Nhà Đà Nẵng (DHA), hoạt động tại HCMC với D-Aqua là dự án chính.",
        "operations": 3,
        "operations_note": "D-Aqua vừa BG 2025, chưa đủ dữ liệu vận hành. Thiết kế ven sông Bến Bình Đông có điểm nhấn.",
        "legal_status": "caution",
        "legal_note": "⚠️ D-Aqua chậm bàn giao ~2–3 năm so với cam kết ban đầu (dự kiến 2022, thực tế 2025). Nguyên nhân: vướng thủ tục phê duyệt phòng cháy. Sổ hồng đang trong quá trình cấp (2025–2026).",
        "delivery_risk": "medium",
        "delivery_note": "Lịch sử chậm BG đáng kể. Nếu mua thứ cấp cần xác nhận đã có sổ hồng trước khi đặt cọc.",
        "notable": "Giá rẻ nhất Q8 cho dự án 2025. Nhưng cần kiểm tra kỹ pháp lý (sổ hồng, PCCC) trước khi quyết định.",
        "projects_hcm": ["D-Aqua (Q8)"],
    },
    "PVInvest": {
        "rating": 3,
        "credibility": "Công ty con PetroVietnam (Tập đoàn Dầu khí Quốc gia). Pegasuite là dự án BĐS điển hình của PVI.",
        "operations": 3,
        "operations_note": "Vận hành ổn, phong cách quản lý nhà nước. Phí ~9–11k/m². Không có tiêu chuẩn đặc biệt.",
        "legal_status": "clean",
        "legal_note": "Pháp lý sạch, dự án nhà nước liên quan. Pegasuite (2020) có sổ hồng.",
        "delivery_risk": "low",
        "delivery_note": "BG 2020 đúng tiến độ, không ghi nhận vướng mắc.",
        "notable": "Uy tín thương hiệu dầu khí quốc gia. Giá trị dự án ổn định, ít biến động. Phù hợp mua ở thực.",
        "projects_hcm": ["Pegasuite (Q8)"],
    },
    "Dream Home Corp": {
        "rating": 3,
        "credibility": "Công ty CP Nhà Mơ Ước, chuyên phân khúc bình dân-trung cấp. Dream Home Riverside là dự án tiêu biểu Q8.",
        "operations": 2,
        "operations_note": "Vận hành ở mức cơ bản, phí ~7–9k/m². Phản hồi cư dân về bảo trì thang máy và hồ bơi chưa tốt.",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn, Dream Home Riverside (2020) có sổ hồng. Không vụ kiện đáng kể.",
        "delivery_risk": "low",
        "delivery_note": "BG đúng tiến độ, không ghi nhận chậm trễ lớn.",
        "notable": "Giá thấp nhất Q8 (3.6 tỷ cho 2PN 64m²). Phù hợp mua ở thực, tỷ lệ đầu tư thấp do chất lượng vận hành trung bình.",
        "projects_hcm": ["Dream Home Riverside (Q8)"],
    },
    "Novaland / Khải Hoàn Land": {
        "rating": 3,
        "credibility": "Khải Hoàn Land — developer Q11 chuyên phân khúc trung cấp. Không liên quan Novaland.",
        "operations": 3,
        "operations_note": "Khu căn hộ Khải Hoàn Q11 (Lạc Long Quân) vận hành trung bình, phí ~8k/m².",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn. Khu căn hộ Khải Hoàn Q11 có sổ hồng đầy đủ.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG, không rủi ro bàn giao.",
        "notable": "Giá tốt khu vực Q11 trung tâm. Phù hợp ở thực do tiện ích khu vực Lạc Long Quân dày đặc.",
        "projects_hcm": ["Imperial Place Q11 (Khải Hoàn)"],
    },
    "Khải Hoàn Land": {
        "rating": 3,
        "credibility": "Developer chuyên phân khúc trung cấp Q11, Bình Tân. Quy mô vừa, uy tín địa phương.",
        "operations": 3,
        "operations_note": "Vận hành ổn định, phí ~8–10k/m². Phản hồi cư dân trung bình.",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn. Khu căn hộ Khải Hoàn Q11 có sổ hồng đầy đủ.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG, không rủi ro bàn giao.",
        "notable": "Giá tốt khu vực Q11. Phù hợp ở thực nhờ tiện ích Lạc Long Quân.",
        "projects_hcm": ["Khu căn hộ Khải Hoàn (Q11)"],
    },
    "Nam Long + Hankyu Hanshin": {
        "rating": 4,
        "credibility": "Liên doanh Nam Long (VN) + Hankyu Hanshin (Nhật Bản). Akari City là flagship của mô hình đối tác Nhật.",
        "operations": 4,
        "operations_note": "Tiêu chuẩn Nhật Bản về bảo trì và quản lý. Akari City rating 4.2/5 trên Google Maps. Phí ~12–15k/m².",
        "legal_status": "clean",
        "legal_note": "Pháp lý sạch. Akari City Phase 1 đã có sổ hồng từng căn. Phase 2 đang hoàn thiện thủ tục.",
        "delivery_risk": "low",
        "delivery_note": "BG 2021 đúng tiến độ. Lịch sử tốt của Nam Long và Hankyu Hanshin.",
        "notable": "Nội khu 3.8ha, 2 hồ bơi, chuẩn Nhật — giá trị dài hạn tốt nhất Bình Tân trong phân khúc 3.5–4.5 tỷ.",
        "projects_hcm": ["Akari City (Bình Tân)"],
    },
    "Vietpearl Group": {
        "rating": 2,
        "credibility": "Developer nhỏ, ít thông tin công khai. Kingsway Tower là dự án chính tại Bình Tân.",
        "operations": 2,
        "operations_note": "Vận hành cơ bản, phí thấp ~7–8k/m². Phản hồi về bảo trì không đồng đều.",
        "legal_status": "clean",
        "legal_note": "Kingsway Tower (2018) có sổ hồng. Không vụ kiện đáng kể ghi nhận.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG 2018. Không còn rủi ro bàn giao.",
        "notable": "Giá rẻ nhất Bình Tân (3.4 tỷ/2PN). Phù hợp mua ở thực — không phải lựa chọn đầu tư hàng đầu.",
        "projects_hcm": ["Kingsway Tower (Bình Tân)"],
    },
    "IDE": {
        "rating": 2,
        "credibility": "IDE Vietnam LLC — developer nhỏ chuyên nhà ở phổ thông. Green Town Bình Tân là dự án quy mô lớn nhất.",
        "operations": 2,
        "operations_note": "Vận hành tối thiểu, phí thấp ~6–8k/m². Cơ sở hạ tầng Green Town cũ dần theo thời gian.",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn. Green Town Bình Tân (BG 2015–2020) có sổ hồng từng block.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG hoàn toàn. Không rủi ro bàn giao.",
        "notable": "Giá rẻ nhất Bình Tân (3.4 tỷ/2PN 63m²). Mua ở thực hoặc cho thuê giá thấp — không phải lựa chọn đầu tư.",
        "projects_hcm": ["Green Town Bình Tân (Bình Tân)"],
    },
    "Trần Anh Group": {
        "rating": 3,
        "credibility": "Developer chuyên Q2 (nay Thủ Đức). The CBD Premium Home tại Đồng Văn Cống là dự án điển hình.",
        "operations": 3,
        "operations_note": "Vận hành trung bình. The CBD Premium Home phí ~10–12k/m². Phản hồi cư dân ổn về an ninh và tiện ích.",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn. The CBD Premium Home (2020) có sổ hồng. Không vụ kiện đáng kể.",
        "delivery_risk": "low",
        "delivery_note": "BG 2020 đúng tiến độ. Không rủi ro bàn giao.",
        "notable": "Vị trí sát Thủ Thiêm — hưởng lợi trực tiếp từ phát triển trung tâm tài chính mới HCMC dài hạn.",
        "projects_hcm": ["The CBD Premium Home (Thủ Đức)"],
    },
    "Nam Long + Nishi Nippon RR": {
        "rating": 4,
        "credibility": "Liên doanh Nam Long + Nishi Nippon Railroad (Nhật). Mizuki Park là đô thị tích hợp 26ha tại Bình Chánh.",
        "operations": 4,
        "operations_note": "Tiêu chuẩn Nhật — Mizuki Park vận hành bởi Nam Long, phí ~11–13k/m². Khu đô thị có trường học, TTTM nội khu.",
        "legal_status": "clean",
        "legal_note": "Pháp lý sạch. Mizuki Park Phase 1–2 đã có sổ hồng. Dự án được chính quyền TP ủng hộ quy hoạch.",
        "delivery_risk": "low",
        "delivery_note": "BG 2020 đúng tiến độ. Mô hình liên doanh Nhật đảm bảo cam kết bàn giao.",
        "notable": "Tốt nhất Bình Chánh cho phân khúc 3.5–4 tỷ. Trục Nguyễn Văn Linh mở rộng sẽ kéo giá khu vực lên.",
        "projects_hcm": ["Mizuki Park (Bình Chánh)"],
    },
    "CTL Corp": {
        "rating": 2,
        "credibility": "Công ty CP Kho Vận Miền Nam Lạnh, chuyển sang BĐS. CTL Tower Q12 là dự án điển hình — quy mô nhỏ.",
        "operations": 2,
        "operations_note": "Vận hành cơ bản. Phí thấp ~7–9k/m². Thiếu chuyên nghiệp so với các developer lớn.",
        "legal_status": "clean",
        "legal_note": "CTL Tower (2019) có sổ hồng. Không vụ kiện đáng kể.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG 2019. Không rủi ro bàn giao.",
        "notable": "Giá tốt nhất Q12 (4 tỷ/2PN 72m² full NT). Phù hợp mua ở thực nhờ tiện ích Q12 đang phát triển.",
        "projects_hcm": ["CTL Tower (Q12)"],
    },
    "Hưng Thịnh Corp / Novaland": {
        "rating": 3, "credibility": "Xem Hưng Thịnh Corp hoặc Novaland tương ứng.",
        "operations": 3, "operations_note": "",
        "legal_status": "caution", "legal_note": "Xem trang chủ đầu tư tương ứng.",
        "delivery_risk": "medium", "delivery_note": "",
        "notable": "", "projects_hcm": [],
    },
}

# Rating → màu sắc
def dev_rating_color(rating: int) -> tuple[str, str]:
    """(fg, bg) theo mức rating 1–5"""
    if rating >= 5:   return ("#166534", "#dcfce7")   # xanh đậm
    elif rating >= 4: return ("#1e40af", "#dbeafe")   # xanh dương
    elif rating >= 3: return ("#92400e", "#fef3c7")   # vàng
    else:             return ("#991b1b", "#fee2e2")    # đỏ

def legal_color(status: str) -> tuple[str, str]:
    """(fg, bg) cho legal_status"""
    return {
        "clean":   ("#166534", "#dcfce7"),
        "caution": ("#92400e", "#fef3c7"),
        "warning": ("#991b1b", "#fee2e2"),
        "red":     ("#fff",    "#dc2626"),
    }.get(status, ("#374151", "#f3f4f6"))

def delivery_color(risk: str) -> tuple[str, str]:
    return {
        "low":    ("#166534", "#dcfce7"),
        "medium": ("#92400e", "#fef3c7"),
        "high":   ("#991b1b", "#fee2e2"),
    }.get(risk, ("#374151", "#f3f4f6"))

def legal_label(status: str) -> str:
    return {"clean": "Sạch", "caution": "Cần thẩm định", "warning": "Cảnh báo", "red": "Đỏ"}.get(status, "—")

def delivery_label(risk: str) -> str:
    return {"low": "Thấp", "medium": "Trung bình", "high": "Cao"}.get(risk, "—")

def get_developer_info(developer_name: str) -> dict:
    """Lấy thông tin developer, fallback về default nếu không tìm thấy."""
    if not developer_name:
        return None
    # Exact match
    if developer_name in DEVELOPERS:
        return DEVELOPERS[developer_name]
    # Partial match (e.g. "Nam Long + Hankyu Hanshin" in key)
    for key, val in DEVELOPERS.items():
        if developer_name in key or key in developer_name:
            return val
    return None
