"""
developer_db.py — Cơ sở dữ liệu phân tích chủ đầu tư BĐS TP.HCM
Đánh giá: uy tín, chất lượng vận hành, lịch sử pháp lý (cập nhật T5/2026)
"""

# legal_status: "clean" | "caution" | "warning" | "red"
# delivery_risk: "low" | "medium" | "high"
# rating / operations: 1–5

DEVELOPERS = {
    "Vingroup": {
        "rating": 5,
        "credibility": "Tập đoàn tư nhân lớn nhất VN, niêm yết quốc tế (VIC), vốn hóa hàng đầu HOSE.",
        "operations": 5,
        "operations_note": "Vận hành Vinhomes tiêu chuẩn 5★, phần mềm VinHome quản lý tích hợp, an ninh 24/7.",
        "legal_status": "clean",
        "legal_note": "Pháp lý minh bạch, công ty đại chúng phải công bố thông tin định kỳ. Vinhomes Grand Park: mục tiêu cấp 20,000 sổ hồng trước 31/12/2025, Origami đã có sổ đầy đủ, Opus One bàn giao T3/2026. Không có vụ kiện lớn liên quan bàn giao hoặc sổ hồng.",
        "delivery_risk": "low",
        "delivery_note": "Lịch sử đúng tiến độ hoặc sớm hơn cam kết. VGP bàn giao đúng 2020–2022.",
        "notable": "Đối tác Nhật Bản (Samty Corp) tại phân khu Origami & Opus One nâng tiêu chuẩn vận hành lên mức quốc tế.",
        "projects_hcm": ["Vinhomes Grand Park (Thủ Đức)"],
    },
    "Phú Mỹ Hưng Corp": {
        "rating": 5,
        "credibility": "Liên doanh Đài Loan–VN (Central Trading & Development). Chuẩn đô thị quốc tế hơn 30 năm tại HCMC.",
        "operations": 5,
        "operations_note": "Phí quản lý cao (~50–90k/m²/tháng) nhưng chất lượng vận hành xuất sắc. Cộng đồng expat đánh giá tốt nhất TP.",
        "legal_status": "clean",
        "legal_note": "Toàn bộ dự án trong khu PMH có đầy đủ pháp lý. Sổ hồng vĩnh viễn, không vướng tranh chấp. Không có ghi nhận vi phạm pháp luật trong 30+ năm hoạt động.",
        "delivery_risk": "low",
        "delivery_note": "Không có ghi nhận chậm bàn giao trong lịch sử 30+ năm hoạt động.",
        "notable": "Sky Garden, Riverside Residence trong khu PMH — chuẩn cao nhất phân khúc 3–10 tỷ Q7.",
        "projects_hcm": ["Sky Garden 3 (Q7)", "Riverside Residence (Q7)"],
    },
    "Nam Long Group": {
        "rating": 4,
        "credibility": "Niêm yết (NLG), chuyên phân khúc vừa túi tiền & đô thị tích hợp. Đối tác Nhật: Hankyu Hanshin, Nishi Nippon RR.",
        "operations": 4,
        "operations_note": "Quản lý chuyên nghiệp, thương hiệu EZ Land cho phân khúc mid-end. Phí vận hành hợp lý ~10–15k/m².",
        "legal_status": "clean",
        "legal_note": "Công ty đại chúng, pháp lý minh bạch. Akari City Phase 1 & 2 đã trao 3,000+ sổ hồng năm 2024. Mizuki Park MP1–MP5 có 2,500+ sổ hồng đã cấp. Không có vụ kiện hay vi phạm pháp lý đáng kể.",
        "delivery_risk": "low",
        "delivery_note": "Bàn giao đúng hoặc trễ nhẹ (≤3 tháng). Ehome 3 (2016), Akari (2021), Mizuki (2020) đều đúng tiến độ.",
        "notable": "Mô hình đô thị xanh tích hợp cùng đối tác Nhật là lợi thế khác biệt dài hạn. EZ Land (Hausneo, Hausbelo) là brand mid-end chất lượng.",
        "projects_hcm": ["Akari City (Bình Tân)", "EHome 3 (Bình Tân)", "Mizuki Park (Bình Chánh)", "Hausneo (Thủ Đức)", "Hausbelo (Thủ Đức)"],
    },
    "EZ Land (Nam Long)": {
        "rating": 4,
        "credibility": "Thương hiệu con của Nam Long Group, chuyên phân khúc mid-end Thủ Đức (Q9 cũ). Được hỗ trợ bởi uy tín NLG.",
        "operations": 4,
        "operations_note": "Tương đương tiêu chuẩn Nam Long, cùng hệ thống quản lý. Hausneo có phí vận hành ~12k/m²/tháng.",
        "legal_status": "clean",
        "legal_note": "Pháp lý sạch, kế thừa từ Nam Long Group. Hausneo đã có sổ hồng từng căn. Không có vi phạm hoặc tranh chấp pháp lý ghi nhận.",
        "delivery_risk": "low",
        "delivery_note": "Hausneo bàn giao Q3/2021 đúng cam kết. Hausbelo đang xây, dự kiến 2026.",
        "notable": "Giá tốt nhất khu vực Q9 cũ — Thủ Đức với tiêu chuẩn đối tác Nhật. Thích hợp đầu tư cho thuê dài hạn.",
        "projects_hcm": ["Hausneo (Thủ Đức)", "Hausbelo (Thủ Đức)"],
    },
    "Gamuda Land": {
        "rating": 4,
        "credibility": "Tập đoàn Malaysia niêm yết quốc tế (Gamuda Berhad). Top 5 developer ASEAN về đô thị xanh.",
        "operations": 5,
        "operations_note": "Tiêu chuẩn ASEAN — Celadon City vận hành bởi Gamuda Property Management, rating 4.5★ trên Google Reviews.",
        "legal_status": "caution",
        "legal_note": "⚠️ Gamuda Land bị phạt hành chính 900 triệu đồng (T4/2023) do ký hợp đồng mua bán trước khi có đủ điều kiện kinh doanh nhà hình thành trong tương lai. Quan trọng hơn: ~927 căn hộ Ruby (Celadon City) chưa được cấp sổ hồng tính đến T5/2026 vì Gamuda Land chưa nộp 514 tỷ đồng truy thu theo kết luận Thanh tra Chính phủ từ năm 2017. Gamuda đã khiếu nại nhưng Thanh tra Chính phủ duy trì quyết định. Các block khác (Emerald, Sapphire, Diamond đã hoàn chỉnh) đã có sổ — kiểm tra kỹ block cụ thể trước khi giao dịch.",
        "delivery_risk": "low",
        "delivery_note": "Bàn giao đúng cam kết theo từng phân khu. Khu Emerald, Sapphire, Diamond đã hoàn thành đúng tiến độ. Ruby là phân khu cần chú ý pháp lý.",
        "notable": "Khu đô thị 82ha chuẩn Malaysia — tiêu chuẩn sống cao nhất Tân Phú. Cộng đồng cư dân ổn định. Luôn xác nhận sổ hồng cụ thể của căn trước khi mua.",
        "projects_hcm": ["Celadon City (Tân Phú)"],
    },
    "Him Lam Land": {
        "rating": 4,
        "credibility": "Thành viên Tập đoàn Him Lam, hoạt động BĐS từ 1994. Uy tín lâu đời tại HCMC và Hà Nội.",
        "operations": 4,
        "operations_note": "Vận hành ổn định, phí quản lý trung bình ~10–12k/m². Cư dân Dragon City đánh giá tốt về an ninh và cảnh quan.",
        "legal_status": "clean",
        "legal_note": "Pháp lý sạch qua các dự án. Him Lam Riverside và Dragon Hill 2 đều có sổ hồng đầy đủ. Vướng mắc nhỏ: bãi đậu xe tầng hầm (Him Lam Chợ Lớn) chậm cấp giấy chứng nhận quyền sở hữu — UBND TP.HCM đã đồng ý giải quyết T5/2025, đang thực hiện.",
        "delivery_risk": "low",
        "delivery_note": "Lịch sử 30 năm không có ghi nhận chậm bàn giao đáng kể. Dragon Hill 2 bàn giao 2020 đúng kế hoạch.",
        "notable": "Dragon City (Him Lam Riverside + Dragon Hill 1&2) là quần thể 3 dự án lớn nhất Nhà Bè — thanh khoản cao, cộng đồng ổn định.",
        "projects_hcm": ["Him Lam Riverside (Nhà Bè)", "Dragon Hill 2 (Nhà Bè)", "Him Lam Chợ Lớn (Q6)"],
    },
    "TTC Land": {
        "rating": 3,
        "credibility": "Công ty con Tập đoàn TTC (Thành Thành Công). Niêm yết (SCR). Chuyên chuỗi Carillon, Charmington.",
        "operations": 4,
        "operations_note": "Vận hành chuỗi Carillon tốt, phí quản lý ~10–13k/m². Carillon 5 & 7 được cư dân đánh giá 4/5 về bảo trì.",
        "legal_status": "caution",
        "legal_note": "⚠️ TTC Land đang vướng thủ tục pháp lý tại nhiều dự án. Carillon 7: chưa xác định rõ nghĩa vụ phí sử dụng đất, điều kiện cấp sổ hồng chưa đầy đủ theo thông tin thị trường. Charmington Iris và Charmington Dragonic đang trong quá trình gỡ vướng pháp lý (ưu tiên năm 2025–2026). ĐHCĐ 2025 TTC Land xác nhận ưu tiên số 1 là hoàn thiện pháp lý các dự án tồn đọng. Carillon 5 (BG 2018) đã có sổ hồng ổn định.",
        "delivery_risk": "medium",
        "delivery_note": "Carillon 5 và một số dự án đã BG ổn định. Dự án mới/chưa hoàn thiện pháp lý có rủi ro chậm sổ hồng. Cần xác nhận tình trạng sổ hồng cụ thể trước giao dịch.",
        "notable": "Carillon 5 là lựa chọn an toàn nhất trong danh mục TTC. Tránh mua Carillon 7 thứ cấp khi chưa xác nhận sổ hồng chính chủ.",
        "projects_hcm": ["Carillon 7 (Tân Phú)", "Carillon 5 (Tân Phú)", "Charmington Tân Bình (Tân Bình)"],
    },
    "Hưng Thịnh Corp": {
        "rating": 2,
        "credibility": "Từng top 5 developer VN theo doanh số. Hiện đang tái cơ cấu tài chính sau khủng hoảng 2022–2025. Lỗ 2,865 tỷ (2023) và 1,139 tỷ (2024). Tổng nợ ~69,195 tỷ đồng.",
        "operations": 3,
        "operations_note": "Vận hành trung bình, phí ~10k/m². Moonlight Residences được đánh giá ổn. Q7 Saigon Riverside chưa có nhiều phản hồi (mới BG 2022).",
        "legal_status": "warning",
        "legal_note": "🚨 T2/2026 Thanh tra Chính phủ chuyển hồ sơ vi phạm phát hành trái phiếu của 3 công ty thuộc hệ sinh thái Hưng Thịnh sang Bộ Công an: Hưng Thịnh Land, Hưng Thịnh Investment, Hưng Thịnh Quy Nhơn. Các vi phạm: thu tiền trước ngày phát hành trái phiếu, sử dụng tiền sai mục đích (chuyển sang đặt cọc mua cổ phần chưa hoàn tất từ 2021). Vụ việc đang trong giai đoạn xem xét điều tra hình sự. Dự án đã BG trước 2022 (Q7 Riverside, Moonlight) có sổ hồng — rủi ro thứ cấp thấp hơn.",
        "delivery_risk": "high",
        "delivery_note": "Dự án đã BG trước 2022: ổn định, có sổ hồng. Dự án mới/đang xây: rủi ro rất cao do tình hình tài chính và hồ sơ hình sự đang điều tra. Không nên đặt cọc dự án Hưng Thịnh chưa BG.",
        "notable": "Chỉ giao dịch thứ cấp các dự án đã BG và có sổ hồng. Tuyệt đối không đặt cọc dự án mới trong giai đoạn điều tra.",
        "projects_hcm": ["Q7 Saigon Riverside (Q7)", "Moonlight Residences (Thủ Đức)"],
    },
    "Novaland": {
        "rating": 2,
        "credibility": "Từng top 3 developer VN. Đang tái cơ cấu nợ trái phiếu hàng chục nghìn tỷ. Đến cuối 2026 mới đủ tiền trả nợ.",
        "operations": 3,
        "operations_note": "Dự án đã BG (Sunrise City View 2015, The Sun Avenue 2018, Richstar 2018) vận hành bởi Novaland Services — chất lượng trung bình–tốt. Phí ~12–18k/m².",
        "legal_status": "warning",
        "legal_note": "🚨 T10/2025 Thanh tra Chính phủ chuyển vi phạm phát hành trái phiếu của Novaland sang Bộ Công an. Phạm vi: 18 công ty con phát hành 131 mã trái phiếu trị giá 67,100 tỷ đồng — vi phạm quy định sử dụng vốn. Tổng dư nợ còn lại ~19,559 tỷ (T9/2025), trả được 44% so với đỉnh. Novaland cho biết đến cuối 2026 mới đủ tiền trả nợ do vướng pháp lý dự án. Dự án đã BG trong danh sách (Richstar, Sun Avenue, Sunrise City View) đều có sổ hồng — an toàn giao dịch thứ cấp. KHÔNG mua dự án Novaland chưa BG.",
        "delivery_risk": "high",
        "delivery_note": "Dự án đã BG: an toàn. Dự án mới/chưa BG: rủi ro rất cao do tài chính và hồ sơ hình sự đang xử lý. Các dự án trong danh sách đều đã BG trước 2022.",
        "notable": "Mua thứ cấp dự án đã BG của Novaland là an toàn. Tuyệt đối không đặt cọc dự án mới cho đến khi tình hình tài chính và pháp lý được làm rõ.",
        "projects_hcm": ["Sunrise City View (Q7)", "The Sun Avenue (Thủ Đức)", "Richstar (Tân Phú)"],
    },
    "Quốc Cường Gia Lai": {
        "rating": 2,
        "credibility": "Niêm yết (QCG). Chủ yếu hoạt động BĐS Q7 và các tỉnh. Năm 2024 gặp biến cố pháp lý lớn với lãnh đạo bị bắt.",
        "operations": 3,
        "operations_note": "Lavida Plus và Central Premium vận hành bởi đơn vị thứ 3. Chất lượng phản hồi từ cư dân ở mức trung bình.",
        "legal_status": "warning",
        "legal_note": "🚨 Ngày 18/7/2024 bà Nguyễn Thị Như Loan (Chủ tịch HĐQT kiêm CEO) bị khởi tố và bắt tạm giam. Tội danh: 'Vi phạm quy định về quản lý, sử dụng tài sản Nhà nước gây thất thoát, lãng phí' — liên quan vụ mua khu đất thuộc Tập đoàn Cao su VN tại Q7 không qua đấu giá. Cổ phiếu QCG giảm mạnh sau sự kiện. Lavida Plus (Q7, BG 2021) và Central Premium (Q8, BG 2019) là dự án đã BG có sổ hồng — ít ảnh hưởng trực tiếp. Cần thẩm định kỹ trước khi giao dịch.",
        "delivery_risk": "high",
        "delivery_note": "Dự án mới của QCG có rủi ro rất cao. Lavida Plus và Central Premium đã BG — an toàn hơn cho giao dịch thứ cấp.",
        "notable": "Chỉ mua thứ cấp các dự án đã BG và có sổ hồng. Tuyệt đối không đặt cọc dự án mới hoặc chuyển nhượng hợp đồng.",
        "projects_hcm": ["Lavida Plus (Q7)", "Central Premium (Q8)"],
    },
    "Sunshine Group": {
        "rating": 3,
        "credibility": "Tập đoàn tư nhân quy mô lớn, đang mở rộng HCMC từ 2019. Sunshine Sky City là dự án flagship Q7.",
        "operations": 3,
        "operations_note": "Chưa có nhiều dự án BG tại HCMC để đánh giá vận hành. Sunshine Group tại HN có phí quản lý cao ~18–25k/m².",
        "legal_status": "caution",
        "legal_note": "⚠️ 12 công ty liên quan Sunshine Group nợ trái phiếu >18,000 tỷ đồng (T11/2025), ~14,000 tỷ đáo hạn cuối 2025–2026 — áp lực cao. Sunshine Sky City Q7 đã gỡ được 'điểm nghẽn' pháp lý T6/2025 (2 dự án tổ hợp được tháo vướng), tower S1 đã vận hành, S2–S4 đến mái. Bị Hòa Bình Construction thi hành án 158 tỷ (T7/2024). Sunshine Sky City chưa BG nên chưa phát sinh vướng mắc sổ hồng.",
        "delivery_risk": "medium",
        "delivery_note": "Sunshine Sky City dự kiến BG từ Q4/2025 trở đi. Rủi ro trái phiếu đáo hạn có thể ảnh hưởng tiến độ. Cần theo dõi tiến độ xây dựng và tình hình tài chính.",
        "notable": "Dự án off-plan — nên mua khi đã ký HĐMB chính thức và có tiến độ xây dựng rõ ràng. Theo dõi khả năng trả trái phiếu năm 2026.",
        "projects_hcm": ["Sunshine Sky City (Q7)"],
    },
    "Vạn Thái Land": {
        "rating": 3,
        "credibility": "Developer quy mô vừa chuyên thị trường Q8 và Tân Phú. Topaz Elite và Topaz Garden là sản phẩm chủ lực.",
        "operations": 3,
        "operations_note": "Vận hành trung bình, phí ~8–10k/m². Topaz Elite được đánh giá 3.5/5 về bảo trì và dịch vụ.",
        "legal_status": "clean",
        "legal_note": "Topaz Elite (Q8, BG 2019) có đầy đủ sổ hồng vĩnh viễn từng căn. UBND Q8 phê duyệt quy hoạch chi tiết dự án theo Quyết định 4279/QĐ-UBND. Không có vụ kiện hay vi phạm pháp lý đáng kể liên quan Topaz Elite. Lưu ý: Topaz City (dự án khác, không phải Topaz Elite) từng bị Thanh tra TPHCM phát hiện vi phạm — không phải cùng dự án.",
        "delivery_risk": "low",
        "delivery_note": "Tất cả dự án trong danh sách đã BG và có sổ hồng. Rủi ro thứ cấp thấp.",
        "notable": "Giá tốt nhất Q8 cho phân khúc 3–4 tỷ. Phù hợp đầu tư cho thuê nhờ thanh khoản ổn định.",
        "projects_hcm": ["Topaz Elite (Q8)", "Topaz Garden (Tân Phú)"],
    },
    "Hoàng Anh Gia Lai": {
        "rating": 2,
        "credibility": "Tập đoàn HAGL (HAG/HNG) từng lớn mạnh, nay đang thoái lui BĐS để tập trung nông nghiệp. Nợ xấu lớn.",
        "operations": 2,
        "operations_note": "Hoàng Anh Thanh Bình (Q7, 2012) vận hành xuống cấp do thiếu đầu tư tái thiết. Phí quản lý thấp nhưng chất lượng tương đương.",
        "legal_status": "caution",
        "legal_note": "⚠️ HAGL đang tái cơ cấu nợ ~28,000 tỷ với các ngân hàng. Dự án Hoàng Anh Thanh Bình (BG 2012) đã có sổ hồng — an toàn giao dịch. Không liên quan trực tiếp đến nợ nhóm. Rủi ro chính: chất lượng vận hành và thanh khoản thứ cấp giảm do thương hiệu mờ dần.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG từ 2012, không có rủi ro bàn giao. Rủi ro chính là chất lượng vận hành và thanh khoản thứ cấp.",
        "notable": "Giá thứ cấp rất tốt do thương hiệu mờ dần. Phù hợp mua ở thực, không phù hợp đầu tư lướt sóng.",
        "projects_hcm": ["Hoàng Anh Thanh Bình (Q7)"],
    },
    "Đức Khải": {
        "rating": 2,
        "credibility": "Developer chủ yếu khu Q7-PMH. Era Town (BG 2014) là dự án lớn nhất. Công ty gặp nhiều khó khăn tài chính nghiêm trọng sau 2018.",
        "operations": 2,
        "operations_note": "Vận hành Era Town ở mức trung bình thấp, thiếu đầu tư nâng cấp. Phản hồi cư dân về bảo trì không tốt.",
        "legal_status": "warning",
        "legal_note": "🚨 Era Town — dự án 9 block / ~3,200 căn (BG 2014) bị nợ sổ hồng hơn 10 năm cho hàng nghìn hộ dân. Nguyên nhân: Đức Khải thế chấp quyền sử dụng đất và tài sản hình thành trong tương lai các block cho ngân hàng vay >4,000 tỷ đồng, chưa giải chấp khi bán căn hộ cho người mua. Ngoài ra Đức Khải nợ thuế >560 tỷ đồng (quá hạn 90 ngày), bị công khai bêu tên. Bị cáo buộc chiếm giữ quỹ bảo trì của cư dân. Theo chỉ đạo UBND TP.HCM đầu 2026 áp dụng cơ chế 'tách rời trách nhiệm', các hộ đã hoàn thành nghĩa vụ tài chính sẽ được ưu tiên cấp sổ hồng — dự kiến giải quyết Q1/2026. Chưa có kết luận khởi tố hình sự cụ thể tính đến T5/2026.",
        "delivery_risk": "low",
        "delivery_note": "Era Town đã BG 2014 — không còn rủi ro bàn giao vật lý. Rủi ro pháp lý (sổ hồng) đang dần được tháo gỡ theo lộ trình Q1/2026. Thanh khoản thứ cấp thấp.",
        "notable": "Giá thứ cấp rẻ nhất PMH-adjacent nhưng kèm rủi ro sổ hồng lâu dài. Nếu mua cần xác nhận căn cụ thể ĐÃ được cấp sổ hồng trước khi đặt cọc.",
        "projects_hcm": ["Era Town (Q7)"],
    },
    "CII": {
        "rating": 3,
        "credibility": "Công ty Cổ phần Đầu tư Hạ tầng Kỹ thuật TP.HCM (CII), niêm yết. Chuyên hạ tầng và BĐS ven sông.",
        "operations": 3,
        "operations_note": "City Gate Towers và Diamond Riverside vận hành bởi đơn vị độc lập. Chất lượng trung bình, phí ~9–11k/m².",
        "legal_status": "caution",
        "legal_note": "⚠️ Diamond Riverside (BG 2022, Q8): tính đến T5/2025 sổ hồng chưa được cấp cho cư dân, CII đang hoàn thiện các thủ tục pháp lý, dự kiến cấp sổ cuối 2025–đầu 2026. City Gate Towers (Q8) có sổ hồng đầy đủ. Không có vi phạm hình sự hay tranh chấp lớn. CII là công ty đại chúng với khung quản trị minh bạch.",
        "delivery_risk": "low",
        "delivery_note": "Các dự án đã BG đúng tiến độ. Diamond Riverside BG 2022 đúng hạn nhưng sổ hồng chậm. Cần xác nhận sổ hồng khi giao dịch Diamond Riverside.",
        "notable": "Lợi thế lớn: dự án cải tạo Kênh Đôi 7,300 tỷ sẽ nâng giá trị khu vực đáng kể sau 2026–2027. Giao dịch Diamond Riverside thứ cấp cần kiểm tra sổ hồng căn cụ thể.",
        "projects_hcm": ["City Gate Towers (Q8)", "Diamond Riverside (Q8)"],
    },
    "Xuân Mai Corp": {
        "rating": 3,
        "credibility": "Tập đoàn Xuân Mai, chuyên xây dựng và phát triển nhà ở thương mại/xã hội. Eco Green Saigon là flagship HCMC.",
        "operations": 3,
        "operations_note": "Vận hành Eco Green Saigon bởi đơn vị nội bộ. Công viên nội khu 5,000m² là điểm nhấn. Phí ~11–13k/m².",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn, không có vụ kiện đáng kể. Eco Green Saigon (BG 2022) đang cấp sổ hồng theo từng block. Không có vi phạm hoặc tranh chấp pháp lý đáng kể ghi nhận.",
        "delivery_risk": "low",
        "delivery_note": "BG 2022 đúng tiến độ. Một số căn chậm sổ hồng ~6 tháng so với cam kết — không nghiêm trọng.",
        "notable": "Tỷ lệ xanh hóa cao nhất Q7 — lợi thế lớn trong dài hạn. Thanh khoản cho thuê tốt nhờ cộng đồng sinh thái.",
        "projects_hcm": ["Eco Green Saigon (Q7)"],
    },
    "DRH Corp": {
        "rating": 3,
        "credibility": "Công ty CP Đầu tư Căn nhà Mơ Ước (DRH Holdings), niêm yết (DRH). Quy mô vừa, chuyên Q8.",
        "operations": 3,
        "operations_note": "Aurora Residences (BG T8/2025) còn khá mới, chưa đủ thời gian đánh giá vận hành. Phản hồi ban đầu của cư dân ổn.",
        "legal_status": "caution",
        "legal_note": "⚠️ Aurora Residences chậm BG ~2 năm (dự kiến Q2/2023, thực tế T8/2025) do vướng mắc thủ tục. DRH Holdings bị cưỡng chế thuế >6 tỷ đồng. Năm 2022 bị xử phạt vi phạm kinh doanh BĐS (đã khắc phục). Công ty đại chúng, đã hoàn thiện pháp lý và cam kết BG T8/2025. Sổ hồng đang trong quá trình cấp sau BG.",
        "delivery_risk": "medium",
        "delivery_note": "Lịch sử chậm BG đáng kể (~2 năm). Đã BG T8/2025 thực tế. Nếu mua thứ cấp cần xác nhận đã có sổ hồng trước khi đặt cọc.",
        "notable": "Giá tốt Q8 cho dự án 2025. Cần kiểm tra kỹ pháp lý sổ hồng căn cụ thể do lịch sử vi phạm và chậm BG.",
        "projects_hcm": ["Aurora Residences (Q8)"],
    },
    "DHA Corp": {
        "rating": 3,
        "credibility": "Công ty CP Đầu tư & Phát triển Nhà Đà Nẵng (DHA), hoạt động tại HCMC với D-Aqua là dự án chính.",
        "operations": 3,
        "operations_note": "D-Aqua vừa BG 2025, chưa đủ dữ liệu vận hành. Thiết kế ven sông Bến Bình Đông có điểm nhấn.",
        "legal_status": "caution",
        "legal_note": "⚠️ D-Aqua chậm bàn giao ~2–3 năm so với cam kết ban đầu (dự kiến 2022, thực tế 2025). Nguyên nhân: vướng thủ tục phê duyệt phòng cháy chữa cháy (PCCC). Sổ hồng đang trong quá trình cấp (2025–2026). Không có vi phạm pháp lý hình sự ghi nhận.",
        "delivery_risk": "medium",
        "delivery_note": "Lịch sử chậm BG đáng kể. Nếu mua thứ cấp cần xác nhận đã có sổ hồng trước khi đặt cọc.",
        "notable": "Giá rẻ nhất Q8 cho dự án 2025. Cần kiểm tra kỹ pháp lý PCCC và sổ hồng trước khi quyết định.",
        "projects_hcm": ["D-Aqua (Q8)"],
    },
    "PVInvest": {
        "rating": 3,
        "credibility": "Công ty con PetroVietnam (Tập đoàn Dầu khí Quốc gia). The Pegasuite là dự án BĐS điển hình của PVInvest.",
        "operations": 3,
        "operations_note": "Vận hành ổn, phong cách quản lý chuyên nghiệp. Phí ~9–11k/m². Không có tiêu chuẩn đặc biệt.",
        "legal_status": "clean",
        "legal_note": "Pháp lý sạch. The Pegasuite (BG 2020) đã trao sổ hồng cho cư dân chỉ sau hơn 1 năm nhận bàn giao — được Báo Tiền Phong và Thanh Niên ghi nhận. Không có vi phạm hoặc tranh chấp pháp lý đáng kể. Uy tín nhà nước bảo đảm.",
        "delivery_risk": "low",
        "delivery_note": "BG 2020 đúng tiến độ. Sổ hồng cấp nhanh (trong vòng 1 năm sau BG). Không ghi nhận vướng mắc.",
        "notable": "Uy tín thương hiệu dầu khí quốc gia. Giá trị dự án ổn định, ít biến động. Phù hợp mua ở thực và đầu tư cho thuê dài hạn.",
        "projects_hcm": ["The Pegasuite (Q8)"],
    },
    "Dream Home Corp": {
        "rating": 3,
        "credibility": "Công ty CP Nhà Mơ Ước, chuyên phân khúc bình dân-trung cấp. Dream Home Riverside là dự án tiêu biểu Q8.",
        "operations": 2,
        "operations_note": "Vận hành ở mức cơ bản, phí ~7–9k/m². Phản hồi cư dân về bảo trì thang máy và hồ bơi chưa tốt.",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn, Dream Home Riverside (BG 2020) có sổ hồng đầy đủ. Không có vi phạm hoặc tranh chấp pháp lý đáng kể ghi nhận.",
        "delivery_risk": "low",
        "delivery_note": "BG đúng tiến độ, không ghi nhận chậm trễ lớn.",
        "notable": "Giá thấp nhất Q8 (3.6 tỷ cho 2PN 64m²). Phù hợp mua ở thực, tỷ lệ đầu tư thấp do chất lượng vận hành trung bình.",
        "projects_hcm": ["Dream Home Riverside (Q8)"],
    },
    "Novaland / Khải Hoàn Land": {
        "rating": 3,
        "credibility": "Khải Hoàn Land — developer Q11 chuyên phân khúc trung cấp. Không liên quan Novaland.",
        "operations": 3,
        "operations_note": "Khu căn hộ Khải Hoàn Q11 (Lạc Long Quân) vận hành trung bình, phí ~8k/m².",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn. Khu căn hộ Khải Hoàn Q11 (Imperial Place — Lạc Long Quân) có sổ hồng đầy đủ. Không có vi phạm hoặc tranh chấp pháp lý đáng kể.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG, không rủi ro bàn giao.",
        "notable": "Giá tốt khu vực Q11 trung tâm. Phù hợp ở thực do tiện ích khu vực Lạc Long Quân dày đặc.",
        "projects_hcm": ["Imperial Place Q11 (Khải Hoàn)"],
    },
    "Khải Hoàn Land": {
        "rating": 3,
        "credibility": "Developer chuyên phân khúc trung cấp Q11, Bình Tân. Quy mô vừa, uy tín địa phương ổn định.",
        "operations": 3,
        "operations_note": "Vận hành ổn định, phí ~8–10k/m². Phản hồi cư dân trung bình.",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn. Khu căn hộ Khải Hoàn Q11 (Imperial Place) có sổ hồng đầy đủ. Khải Hoàn Prime (dự án mới) đang hoàn thiện thủ tục pháp lý (UBND TP.HCM phê duyệt thay đổi mục đích sử dụng đất T7/2025), dự kiến BG 2028. Không có vi phạm hoặc tranh chấp pháp lý đáng kể.",
        "delivery_risk": "low",
        "delivery_note": "Dự án Imperial Place đã BG, không rủi ro. Khải Hoàn Prime là dự án mới, cần theo dõi.",
        "notable": "Giá tốt khu vực Q11. Phù hợp ở thực nhờ tiện ích Lạc Long Quân.",
        "projects_hcm": ["Khu căn hộ Khải Hoàn (Q11)"],
    },
    "Nam Long + Hankyu Hanshin": {
        "rating": 4,
        "credibility": "Liên doanh Nam Long (VN) + Hankyu Hanshin (Nhật Bản). Akari City là flagship của mô hình đối tác Nhật.",
        "operations": 4,
        "operations_note": "Tiêu chuẩn Nhật Bản về bảo trì và quản lý. Akari City rating 4.2/5 trên Google Maps. Phí ~12–15k/m².",
        "legal_status": "clean",
        "legal_note": "Pháp lý sạch. Akari City Phase 1 đã có sổ hồng đầy đủ. Phase 2 bàn giao T10/2024 và đang hoàn thiện thủ tục cấp sổ theo lô. Tổng 3,000+ sổ hồng đã trao năm 2024. Không có vi phạm hoặc tranh chấp pháp lý.",
        "delivery_risk": "low",
        "delivery_note": "BG 2021 (Phase 1) và T10/2024 (Phase 2) đúng tiến độ. Lịch sử tốt của Nam Long và Hankyu Hanshin.",
        "notable": "Nội khu 3.8ha, 2 hồ bơi, chuẩn Nhật — giá trị dài hạn tốt nhất Bình Tân trong phân khúc 3.5–4.5 tỷ.",
        "projects_hcm": ["Akari City (Bình Tân)"],
    },
    "Vietpearl Group": {
        "rating": 2,
        "credibility": "Developer nhỏ, ít thông tin công khai. Kingsway Tower là dự án chính tại Bình Tân.",
        "operations": 2,
        "operations_note": "Vận hành cơ bản, phí thấp ~7–8k/m². Phản hồi về bảo trì không đồng đều.",
        "legal_status": "clean",
        "legal_note": "Kingsway Tower (BG 2018) có sổ hồng. Không có vụ kiện đáng kể ghi nhận. Developer nhỏ ít thông tin minh bạch.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG 2018. Không còn rủi ro bàn giao.",
        "notable": "Giá rẻ nhất Bình Tân (3.4 tỷ/2PN). Phù hợp mua ở thực — không phải lựa chọn đầu tư hàng đầu.",
        "projects_hcm": ["Kingsway Tower (Bình Tân)"],
    },
    "IDE": {
        "rating": 2,
        "credibility": "IDE Vietnam LLC — developer nhỏ chuyên nhà ở phổ thông. Green Town Bình Tân là dự án quy mô lớn nhất.",
        "operations": 2,
        "operations_note": "Vận hành tối thiểu, phí thấp ~6–8k/m². Cơ sở hạ tầng Green Town cũ dần theo thời gian.",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn. Green Town Bình Tân (BG 2015–2020) có sổ hồng từng block theo lộ trình. Không có vi phạm hoặc tranh chấp pháp lý đáng kể ghi nhận.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG hoàn toàn. Không rủi ro bàn giao.",
        "notable": "Giá rẻ nhất Bình Tân (3.4 tỷ/2PN 63m²). Mua ở thực hoặc cho thuê giá thấp — không phải lựa chọn đầu tư.",
        "projects_hcm": ["Green Town Bình Tân (Bình Tân)"],
    },
    "Trần Anh Group": {
        "rating": 3,
        "credibility": "Developer chuyên Q2 (nay Thủ Đức). The CBD Premium Home tại Đồng Văn Cống là dự án điển hình.",
        "operations": 3,
        "operations_note": "Vận hành trung bình. The CBD Premium Home phí ~10–12k/m². Phản hồi cư dân ổn về an ninh và tiện ích.",
        "legal_status": "clean",
        "legal_note": "Pháp lý ổn. The CBD Premium Home (BG 2020) có sổ hồng. Không có vụ kiện liên quan dự án HCMC. Lưu ý: Trần Anh Group có một số dự án tại tỉnh (Long An, Bình Dương) bị phản ánh chậm sổ hồng và bán trước điều kiện — không áp dụng cho dự án HCMC.",
        "delivery_risk": "low",
        "delivery_note": "The CBD Premium Home BG 2020 đúng tiến độ. Không rủi ro bàn giao.",
        "notable": "Vị trí sát Thủ Thiêm — hưởng lợi trực tiếp từ phát triển trung tâm tài chính mới HCMC dài hạn.",
        "projects_hcm": ["The CBD Premium Home (Thủ Đức)"],
    },
    "Nam Long + Nishi Nippon RR": {
        "rating": 4,
        "credibility": "Liên doanh Nam Long + Nishi Nippon Railroad (Nhật). Mizuki Park là đô thị tích hợp 26ha tại Bình Chánh.",
        "operations": 4,
        "operations_note": "Tiêu chuẩn Nhật — Mizuki Park vận hành bởi Nam Long, phí ~11–13k/m². Khu đô thị có trường học, TTTM nội khu.",
        "legal_status": "clean",
        "legal_note": "Pháp lý sạch. Mizuki Park Phase MP1–MP5 đã có 2,500+ sổ hồng đầy đủ. Dự án được chính quyền TP ủng hộ quy hoạch. Không có vi phạm hoặc tranh chấp pháp lý.",
        "delivery_risk": "low",
        "delivery_note": "BG 2020 đúng tiến độ. Mô hình liên doanh Nhật đảm bảo cam kết bàn giao.",
        "notable": "Tốt nhất Bình Chánh cho phân khúc 3.5–4 tỷ. Trục Nguyễn Văn Linh mở rộng sẽ kéo giá khu vực lên.",
        "projects_hcm": ["Mizuki Park (Bình Chánh)"],
    },
    "CTL Corp": {
        "rating": 2,
        "credibility": "Công ty TNHH Chung Trang Linh, chuyên nhà ở xã hội / tái định cư. CTL Tower Q12 là dự án điển hình — quy mô vừa.",
        "operations": 2,
        "operations_note": "Vận hành cơ bản. Phí thấp ~7–9k/m². Thiếu chuyên nghiệp so với các developer lớn.",
        "legal_status": "clean",
        "legal_note": "CTL Tower (2 block, 368 căn) có sổ hồng được cấp T8/2025 sau khi vướng mắc thủ tục được giải quyết. Trước đó (2024) sổ hồng chưa cấp do vướng thủ tục phối hợp giữa Phòng Đăng ký Đất đai HCMC và Sở Xây dựng. Hiện đã giải quyết, cư dân nhận sổ hồng đầy đủ T8/2025.",
        "delivery_risk": "low",
        "delivery_note": "Dự án đã BG 2019. Sổ hồng đã cấp T8/2025 sau vướng mắc. Không rủi ro bàn giao.",
        "notable": "Giá tốt nhất Q12 (4 tỷ/2PN 72m² full NT). Phù hợp mua ở thực nhờ tiện ích Q12 đang phát triển. Sổ hồng đã có — an toàn giao dịch.",
        "projects_hcm": ["CTL Tower (Q12)"],
    },
    "Hưng Thịnh Corp / Novaland": {
        "rating": 2,
        "credibility": "Xem Hưng Thịnh Corp hoặc Novaland tương ứng — cả hai đều đang bị điều tra trái phiếu.",
        "operations": 3,
        "operations_note": "",
        "legal_status": "warning",
        "legal_note": "🚨 Xem chi tiết trang chủ đầu tư tương ứng: Hưng Thịnh Corp (T2/2026 chuyển Bộ Công an) hoặc Novaland (T10/2025 chuyển Bộ Công an). Cả hai đều có hồ sơ vi phạm phát hành trái phiếu đang được điều tra.",
        "delivery_risk": "high",
        "delivery_note": "",
        "notable": "",
        "projects_hcm": [],
    },
}

# Rating → màu sắc
def dev_rating_color(rating: int) -> tuple[str, str]:
    """(fg, bg) theo mức rating 1–5"""
    if rating >= 5:   return ("#166534", "#dcfce7")   # xanh đậm
    elif rating >= 4: return ("#1e40af", "#dbeafe")   # xanh dương
    elif rating >= 3: return ("#92400e", "#fef3c7")   # vàng
    else:             return ("#991b1b", "#fee2e2")    # đỏ

def legal_color(status: str) -> tuple[str, str]:
    """(fg, bg) cho legal_status"""
    return {
        "clean":   ("#166534", "#dcfce7"),
        "caution": ("#92400e", "#fef3c7"),
        "warning": ("#991b1b", "#fee2e2"),
        "red":     ("#fff",    "#dc2626"),
    }.get(status, ("#374151", "#f3f4f6"))

def delivery_color(risk: str) -> tuple[str, str]:
    return {
        "low":    ("#166534", "#dcfce7"),
        "medium": ("#92400e", "#fef3c7"),
        "high":   ("#991b1b", "#fee2e2"),
    }.get(risk, ("#374151", "#f3f4f6"))

def legal_label(status: str) -> str:
    return {"clean": "Sạch", "caution": "Cần thẩm định", "warning": "Cảnh báo", "red": "Đỏ"}.get(status, "—")

def delivery_label(risk: str) -> str:
    return {"low": "Thấp", "medium": "Trung bình", "high": "Cao"}.get(risk, "—")

def get_developer_info(developer_name: str) -> dict:
    """Lấy thông tin developer, fallback về default nếu không tìm thấy."""
    if not developer_name:
        return None
    # Exact match
    if developer_name in DEVELOPERS:
        return DEVELOPERS[developer_name]
    # Partial match (e.g. "Nam Long + Hankyu Hanshin" in key)
    for key, val in DEVELOPERS.items():
        if developer_name in key or key in developer_name:
            return val
    return None
